# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: CI

on:
    push:
        branches: [develop, main]
    pull_request:
        branches: [develop, main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14
              uses: actions/setup-node@v1
              with:
                  registry-url: https://npm.pkg.github.com/
                  node-version: 14
                  scope: "@farisaziz12"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
            - name: Deploy Package
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                  git config --global user.name "Faris Aziz"
                  git config --global user.email "farisaziz12@gmail.com"
                  npm run release
                  git pull origin main
                  git push --follow-tags origin main
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
